### ISSUE TITLE
add development fixtures

### ISSUE THREAD

**Issue by brylie** [CompanionshipCare/companionship-care#104]
## Task

- [x] add `factory_boy` to this project with `poetry add factory_boy --group dev`
- [x] define the [initial factory_boy factories](https://factoryboy.readthedocs.io/en/stable/index.html?highlight=install#defining-factories)

**Comment by brylie** [comment]
@werberger, would you consider taking this task? Companionship Care is also a Django app, so it would be similar to the CiviWiki codebase. There are a few open tasks in Companionship Care, whereas most tasks in CiviWiki have been claimed.

**Comment by werberger** [comment]
I am definitely interested - the project looks amazing too. Thank you @brylie.

I will look at it in more detail over the coming days.

**Comment by werberger** [comment]
@brylie I've seen the factories defined in different places, where would you prefer them defined?

in _factories_ files within _test_ folders within each app
in _factories_ files within each app
in a _tests_ file at the project level

I think I'm confident resolving the issue just don't want to create more work for someone to move everything.

**Comment by brylie** [comment]
Let's start out with a `factories.py` in each app directory.

**Comment by brylie** [comment]
Let's split out the `Activity` factory into a follow-up task.
