### ISSUE TITLE
Add instructions for resolving conflicts in poetry.lock

### ISSUE THREAD

**Issue by brylie** [CompanionshipCare/companionship-care#119]
Whenever there are simultaneous changes to our project dependencies, there is a high likelihood of conflicts in `poetry.lock`. This issue is not unique to our project and likely happens in every Poetry project with multiple developers.

## Task

- [ ] add instructions for resolving conflicts in `poetry.lock` against the `main` branch

## Example

```sh
# Get poetry.lock to look like it does in master
git checkout --theirs poetry.lock
# Rewrite the lock file
poetry lock --no-update
```

## Resources

- https://www.peterbe.com/plog/how-to-resolve-a-git-conflict-in-poetry.lock
- https://nitaym.github.io/ourstheirs/

Consider adding: https://poetry-merge-lock.readthedocs.io/en/latest/

**Comment by earthcomfy** [comment]
@brylie Since I have faced this issue in my previous PR, I would like to work on this one. Can you assign me? And also, the instructions are going to be added inside [contributing guideline](https://github.com/CompanionshipCare/companionship-care/blob/main/CONTRIBUTING.md) right?

**Comment by brylie** [comment]
Thanks, @earthcomfy. Feel free to use the instructions found in the following pull request.

https://github.com/CiviWiki/OpenCiviWiki/pull/1391
