### ISSUE TITLE
Register all models with Django Admin

### ISSUE THREAD

**Issue by brylie** [CompanionshipCare/companionship-care#129]
We haven't registered all project models with the Django Admin, making it difficult to manage content in a centralized manner.

## Task

For each model in our project,
- [ ] register the model with the Django Admin, if not already registered

## Resources

- https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#modeladmin-objects

**Comment by moazfarrukh** [comment]
can i work on this task?

**Comment by kishan3** [comment]
Fixed in #130
