### ISSUE TITLE
User authentication REST endpoints

### ISSUE THREAD

**Issue by brylie** [CompanionshipCare/companionship-care#170]
Add user authentication REST endpoints.

## Acceptance criteria 

- users can log in and logout via REST 
- the Accounts app contains endpoint definitions/logic 
- adhere closely to Django REST Framework documentation and conventions

**Comment by brylie** [comment]
@werberger, would you like to take this issue? It will serve as the foundation for REST API development in this project.

**Comment by werberger** [comment]
I'm definitely keen @brylie. Happy to give it a go.

**Comment by brylie** [comment]
Hei @werberger 

Let's use Dango REST Registration to make this task easier:

https://django-rest-registration.readthedocs.io/
