### ISSUE TITLE
Old Circle Group Photos aren't deleted

### ISSUE THREAD

**Issue by CHAXZeni** [CompanionshipCare/companionship-care#171]
## Problem Description
When playing around with the website, I noticed that when editing a Circle Group and changing the Circle Group Photo the old photos/thumbnails are not deleted and stay in the media folder.

This screenshot is the media folder after updating the photo a couple of times.
![image](https://user-images.githubusercontent.com/68239498/205771572-dc99c261-5256-4991-bb3e-3b68438571f3.png)

I am updating the photos with the following page.
![image](https://user-images.githubusercontent.com/68239498/205771902-aa3823e3-d444-4336-a36a-0d4e55098ac2.png)

## Discussion
This may not be a major problem right now but over time this may lead to a lot of wasted space.
I think I have a solution for this and would like to spend some time working on it if it is necessary to fix. 

Thanks !!

**Comment by brylie** [comment]
Good catch 🙂

**Comment by CHAXZeni** [comment]
My bad 😅. Can you assign me to it, I'd like to give it a go !!
