### ISSUE TITLE
Users should be redirected to People or their default Caring Circle upon login/register

### ISSUE THREAD

**Issue by brylie** [CompanionshipCare/companionship-care#91]
People who log in and register may see a primarily empty front page. It would be more convenient if they were redirected to one of the following.

- "people" page when they can create more than one caring circle
- "add person" when they have not yet created a Caring Circle
- their default Caring Circle when they have created one and cannot create any more

After some more consideration, I think a solution would look like:

- [x] anonymous user sees a welcome message on the home page (working now)
- [x] redirect all users to the "people" page when logging in
- [x] redirect users to "people" page when signing up
- [x] if a user has not created a Caring Circle, they will see the button "add Person" or "Create Caring Circle"
- [x] if a user is a member of a Caring Circle, it will be listed on the people page (working now)

**Comment by ogdhruv** [comment]
I would like to contribute to solving this issue.
Assign this issue to me, and please describe to me how I should start locating the issue.

**Comment by brylie** [comment]
On reconsideration (and in conjunction with #90), the Home page should have three possible states:

- welcome message for unregistered users
- "create caring circle" message for registered users with no caring circle
- caring circle redirect for users who have created a caring circle

At a later point, we can determine how to handle multiple caring circles per user again.

**Comment by brylie** [comment]
I am closing this as complete. I accidentally committed directly to `main` without realizing it. My bad! I'll set stricter restrictions and be more aware going forward.
